source 'https://github.com/CocoaPods/Specs.git'

target 'XLEasyNetwork_Example', :exclusive => true do
  pod 'XLEasyNetwork', :path => '../'
end

target 'XLEasyNetwork_Tests', :exclusive => true do
  pod 'XLEasyNetwork', :path => '../'

pod 'PureLayout', '~> 1.0.1'

end
